version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: mkdir Games
      - apk add --no cache ca-certificate
      - persist_to_workspace:
          root: /root/project
          paths:
            - Games
         #  - baz
