version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: cd /
      - persist_to_workspace:
          root: /project
          paths:
            - foo/bar
            - baz
