version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: mkdir Games
      - persist_to_workspace:
          root: /root/project/Games
          paths:
            - foo/bar
            - baz
