version: 2.1
jobs:
  job_1:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: mkdir Games
      - run: apk add ca-certificates
      - persist_to_workspace:
          root: /root/project
          paths:
            - Games

  job_2:
    docker: 
      - image: alpine 
    steps:
      - attach_workspace:
          at: /root/project/

workflows:
  workflows_1:
    jobs:
      - job_1
      - job_2
