version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: ls -al
      - run: cd /
      - run: ls -al
      - persist_to_workspace:
          root: /root/project
          paths:
            - foo/bar
            - baz
