version: 2.1
jobs:
  job_1:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: echo "Hello i am groot" >> file1
      - run: echo "Hello i am root" >> file2
      - run: echo "Hello i am tree" >> file3
      - run: echo "Hello i am Leaves" >> file4 
      - run: cd ../../ && ls -al
      - run: apk add ca-certificates
      - persist_to_workspace:
          root: ~/
          paths: project/file1
                 project/file2
                 project/file3
                 project/file4                 

  job_2:
    docker: 
      - image: alpine 
    steps:
      - run: apk add ca-certificates
      - attach_workspace:
          at: myfiles/
          
  job_3:
    docker:
      - image: alpine
    steps:
      - run: echo "In Job_3" 

workflows:
  workflows_1:
    jobs:
      - job_1
      - job_2:
          type: approval
          requires:
            - job_1
      - job_3:
          requires:
            - job_2
