version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: mkdir Games
      - run: apk add ca-certificates
      - persist_to_workspace:
          root: /root/project
          paths:
            - Games/NFS
         #  - baz
