version: 2.1
jobs:
  job_1:
    docker:
      - image: alpine
    steps:
      - run: pwd
      - run: echo "Hello i am groot" >> file1
      - run: apk add ca-certificates
      - persist_to_workspace:
          root: ~/
          paths: project/file1

  job_2:
    docker: 
      - image: alpine 
    steps:
      - run: apk add ca-certificates
      - attach_workspace:
          at: /root/home

workflows:
  workflows_1:
    jobs:
      - job_1
      - job_2:
          requires:
            - job_1
